[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Will Thompson <will@willthompson.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
num-rational = "0.2.2"
